update code/data that preloads site domain to database
codalab/codalab-competitions pull request #3103
Opened 2022-02-10 23:26 UTC by bbearce

Below is my  .env (skip to get to bug and PR discussion):
```
# ----------------------------------------------------------------------------
# Submission processing
# ----------------------------------------------------------------------------
SUBMISSION_TEMP_DIR=/tmp/codalab

# ----------------------------------------------------------------------------
# Storage
# ----------------------------------------------------------------------------

# Uncomment to use Azure
DEFAULT_FILE_STORAGE=codalab.azure_storage.AzureStorage
AZURE_ACCOUNT_NAME=*************************
AZURE_ACCOUNT_KEY=*************************
AZURE_CONTAINER=public
# Only set these if bundle storage key is different from normal account keys
# BUNDLE_AZURE_ACCOUNT_NAME=
# BUNDLE_AZURE_ACCOUNT_KEY=
BUNDLE_AZURE_CONTAINER=bundles

# ----------------------------------------------------------------------------
# Database
# ----------------------------------------------------------------------------

# Used engine (mysql, postgresql, sqlite3, memory)
DB_ENGINE=postgresql

# Connection parameters
DB_HOST=postgres
DB_PORT=5432
DB_NAME=codalab_website
DB_USER=root
DB_PASSWORD=password

# Path where DB files will be mapped
DB_DATA_PATH=./var/data/postgres

# ----------------------------------------------------------------------------
# Caching
# ----------------------------------------------------------------------------
MEMCACHED_PORT=11211

# ----------------------------------------------------------------------------
# RabbitMQ and management
# ----------------------------------------------------------------------------
RABBITMQ_DEFAULT_USER=guest
RABBITMQ_DEFAULT_PASS=guest
BROKER_URL=pyamqp://guest:guest@rabbit:5671//
BROKER_USE_SSL=True
RABBITMQ_PORT=5671
RABBITMQ_MANAGEMENT_PORT=15671

#BROKER_URL=pyamqp://$RABBITMQ_DEFAULT_USER:$RABBITMQ_DEFAULT_PASS@rabbit:5672//
#BROKER_USE_SSL=True
RABBITMQ_HOST=rabbit
#RABBITMQ_PORT=5672
#RABBITMQ_MANAGEMENT_PORT=15672
FLOWER_BASIC_AUTH=root:password
FLOWER_PORT=5555

# ----------------------------------------------------------------------------
# Django/nginx
# ----------------------------------------------------------------------------
DJANGO_SECRET_KEY=change-me-to-a-secret
DJANGO_PORT=8000
DEBUG=True
IS_DEV=True
NGINX_PORT=80

SSL_PORT=443
SSL_CERTIFICATE=/app/certs/fullchain.pem
SSL_CERTIFICATE_KEY=/app/certs/privkey.pem
# Allowed hosts separated by space
SSL_ALLOWED_HOSTS=codalab-python3-test.eastus.cloudapp.azure.com

# Turn on and off "User Switching Middleware" which allows you to change
# users to see any bugs or issues they may be having
#
# ** WARNING ** could be used by malicious user to see other user's private 
# data
USER_SWITCH_MIDDLEWARE=True

# Set this to your actual domain, like example.com
CODALAB_SITE_DOMAIN=codalab-python3-test.eastus.cloudapp.azure.com

# How many site workers (submission result processors)?
WEB_CONCURRENCY=2

# ----------------------------------------------------------------------------
# Logging
# ----------------------------------------------------------------------------
# Make sure LOGGING_DIR doesn't end with a slash
LOGGING_DIR=./var/logs
DJANGO_LOG_LEVEL=debug

# ----------------------------------------------------------------------------
# ChaHub
# ----------------------------------------------------------------------------
# Be sure to include trailing slash on URL
#CHAHUB_API_URL=https://chahub.org/api/v1/
#CHAHUB_API_KEY=some-secret-key
#SOCIAL_AUTH_CHAHUB_BASE_URL=https://chahub.org

EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST=smtp.sendgrid.net
EMAIL_HOST_USER=apikey
EMAIL_HOST_PASSWORD=*********************
EMAIL_PORT=587
EMAIL_USE_TLS=True
DEFAULT_FROM_EMAIL=MedICI <kalpathy@mgh.harvard.edu>
SERVER_EMAIL=kalpathy@mgh.harvard.edu
```

> Start Discussion
--------------------------------------------------------------------------------------------------------------------------

# A brief description of the purpose of the changes contained in this PR.
Upon initial deploy, the django container has run_django.sh executed. This creates database migrations and pre-loads the database with a fixture of json located at *codalab-competitions/codalab/apps/web/fixtures/initial_data.json*. This fixture does nothing to the *sites.site* table which holds the site domain. The default for this table is *example.com* (which [django sites](https://docs.djangoproject.com/en/4.0/ref/contrib/sites/) sets). 

If this is not updated to reflect the real domain, then when CodaLab sends confirmation emails to the applying users, the confirmation link is formatted as "https://example.com/accounts/confirm-email/MQ:1n9XOv:ehbVpB2B7La1QjcByTDZRHuAV0Y/". 

So instead of manually updating this after deploy, this PR aims to automate this action by adding entries in initialize_site.json so that run_django.sh can overwrite them right before the json is loaded into the DB. The values being referenced are environment variable CODALAB_SITE_DOMAIN and it's value. 

Ex (prior to overwriting):
```
{"model":"sites.site","pk":1,"fields":{"domain":"example.com","name":"example.com"}}
```

Ex (after overwriting):
```
{"model":"sites.site","pk":1,"fields":{"domain":"codalab-python3-test.eastus.cloudapp.azure.com","name":"CODALAB_SITE_DOMAIN"}}
```

# A checklist for hand testing
- Set these .env variables before attempting
  * CODALAB_SITE_DOMAIN
  * SSL_ALLOWED_HOSTS
  * BROKER_URL=pyamqp://guest:guest@rabbit:5671//
  * BROKER_USE_SSL=True
  * RABBITMQ_PORT=5671
  * RABBITMQ_MANAGEMENT_PORT=15671
  * EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
  * EMAIL_HOST=smtp.sendgrid.net
  * EMAIL_HOST_USER=apikey
  * EMAIL_HOST_PASSWORD=*******
  * EMAIL_PORT=587
  * EMAIL_USE_TLS=True
  * DEFAULT_FROM_EMAIL=<some email>
  * SERVER_EMAIL=<some email>

# Any relevant files for testing
initial_data.json - edits in PR

# Misc. comments
- If you don't use https, then the redirection email "https://example.com/accounts/confirm-email/MQ:1n9XOv:ehbVpB2B7La1QjcByTDZRHuAV0Y/" will try to use https and the site will not be found. I noticed just reloading the page or pressing enter or somehow forcing the url to use http will work. I ended up using [certbot](https://certbot.eff.org/) to make certs and just secured the site for testing.

- in run_django.sh I decided to use node to do the overwriting of initial_data.json. There is a good bash command tool called [jq](https://stedolan.github.io/jq/) that is nice but I thought it would be better to use the tools we already have versus installing more tools in the main django Dockerfile. As it stands the javascript code is written out in run_django.sh instead of being in a file under  codalab-competitions/scripts. I couldn't tell if adding more files to the overall codalab code base was more clutter versus having a file that is run from run_django.sh. I could easily make a script for this called adjust_site_domain.js if that is cleaner. 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [ ] Code review by reviewer
- [ ] Hand tested by reviewer
- [ ] Ready to merge

2022-02-24 15:25 UTC, Didayolo commented
Associated issue: #3075

2022-03-01 02:57 UTC, Tthomas63 requested changes

2022-03-01 02:57 UTC, Tthomas63 commented on codalab/scripts/initialize_from_fixture.py
> +    json_data[0]['fields']['name'] = 'CODALAB_SITE_DOMAIN'
Probably change `os.environ` -> `os.environ.get` with a default like localhost in-case it's not supplied.

Also it looks like line 6 needs to be changed to either the same environment variable, or a different environment variable for the site "name".

![image](https://user-images.githubusercontent.com/28552312/156096250-0e67c0b6-de45-4d5f-9938-ae4124319364.png)

2022-03-21 14:08 UTC, Tthomas63 approved these changes

2022-03-21 16:17 UTC, Didayolo commented
@Tthomas63 you have approved the changes. But is the PR ready to be merged? Have you hand-tested it?

Thank you.

2022-04-14 14:42 UTC, merged